//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTraining.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcTraining.Resources.SqlResources", typeof(SqlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(Blog_Id) as Blog_Count from Tbl_Blog where Is_Deleted = 0.
        /// </summary>
        internal static string BlogCount {
            get {
                return ResourceManager.GetString("BlogCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(Tbl_Blog.Blog_Id) FROM Tbl_Blog WHERE Blog_Title=@BlogTitle;.
        /// </summary>
        internal static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Blog_Id,Blog_Title,Blog_Author,Blog_Content from Tbl_Blog where Is_Deleted = 0.
        /// </summary>
        internal static string GetAllBlog {
            get {
                return ResourceManager.GetString("GetAllBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Blog_Id
        ///      ,Blog_Title
        ///      ,Blog_Author
        ///      ,Blog_Content
        ///  FROM Tbl_Blog WHERE Blog_Id=@BlogId;.
        /// </summary>
        internal static string GetBlogById {
            get {
                return ResourceManager.GetString("GetBlogById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Tbl_Blog (
        ///  Blog_Title,Blog_Author,Blog_Content,Is_Deleted)
        ///  VALUES (@BlogTitle,@BlogAuthor,@BlogContent,@IsDeleted);.
        /// </summary>
        internal static string SaveBlog {
            get {
                return ResourceManager.GetString("SaveBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Tbl_Blog Set 
        ///Blog_Title=@BlogTitle,Blog_Author=@BlogAuthor,Blog_Content=@BlogContent,Is_Deleted=@IsDeleted
        ///  WHERE Blog_Id=@Id;.
        /// </summary>
        internal static string UpdateBlog {
            get {
                return ResourceManager.GetString("UpdateBlog", resourceCulture);
            }
        }
    }
}
